display:
  title: "Application"
  width: 1600
  height: 900
  pixelSize: 1
  showDemoWindow: false

# dataset: "bunny"
# dataset: "emitter"
# dataset: "deformables"
# dataset: "motor"
# dataset: "simple"
dataset: "doubledambreak2"
