display:
  title: "Application"
  width: 1600
  height: 900
  # width: 1920
  # height: 1080
  pixelSize: 1
  showDemoWindow: false

# dataset: "bunny"
# dataset: "emitter"
# dataset: "deformables"
# dataset: "motor"
dataset: "simple"
# dataset: "doubledambreak2"
# dataset: "dambreak"

datasetFrameCount: 5
particleRadius: 0.1
particleRadiusMultiplier: 2.0
