display:
  title: "Application"
  # width: 1600
  # height: 900
  width: 1200
  height: 800
  pixelSize: 1
  showDemoWindow: false

# dataset: "bunny"
# dataset: "emitter"
# dataset: "deformables"
# dataset: "motor"
dataset: "simple"
